/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RsvpIdRouteImport } from './routes/rsvp/$id'
import { Route as ApiGuestsRouteImport } from './routes/api/guests'
import { Route as ApiOauthStartRouteImport } from './routes/api/oauth/start'
import { Route as ApiOauthCallbackRouteImport } from './routes/api/oauth/callback'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RsvpIdRoute = RsvpIdRouteImport.update({
  id: '/rsvp/$id',
  path: '/rsvp/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGuestsRoute = ApiGuestsRouteImport.update({
  id: '/api/guests',
  path: '/api/guests',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOauthStartRoute = ApiOauthStartRouteImport.update({
  id: '/api/oauth/start',
  path: '/api/oauth/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOauthCallbackRoute = ApiOauthCallbackRouteImport.update({
  id: '/api/oauth/callback',
  path: '/api/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/api/guests': typeof ApiGuestsRoute
  '/rsvp/$id': typeof RsvpIdRoute
  '/api/oauth/callback': typeof ApiOauthCallbackRoute
  '/api/oauth/start': typeof ApiOauthStartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/api/guests': typeof ApiGuestsRoute
  '/rsvp/$id': typeof RsvpIdRoute
  '/api/oauth/callback': typeof ApiOauthCallbackRoute
  '/api/oauth/start': typeof ApiOauthStartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/api/guests': typeof ApiGuestsRoute
  '/rsvp/$id': typeof RsvpIdRoute
  '/api/oauth/callback': typeof ApiOauthCallbackRoute
  '/api/oauth/start': typeof ApiOauthStartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/api/guests'
    | '/rsvp/$id'
    | '/api/oauth/callback'
    | '/api/oauth/start'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/api/guests'
    | '/rsvp/$id'
    | '/api/oauth/callback'
    | '/api/oauth/start'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/api/guests'
    | '/rsvp/$id'
    | '/api/oauth/callback'
    | '/api/oauth/start'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ApiGuestsRoute: typeof ApiGuestsRoute
  RsvpIdRoute: typeof RsvpIdRoute
  ApiOauthCallbackRoute: typeof ApiOauthCallbackRoute
  ApiOauthStartRoute: typeof ApiOauthStartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rsvp/$id': {
      id: '/rsvp/$id'
      path: '/rsvp/$id'
      fullPath: '/rsvp/$id'
      preLoaderRoute: typeof RsvpIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/guests': {
      id: '/api/guests'
      path: '/api/guests'
      fullPath: '/api/guests'
      preLoaderRoute: typeof ApiGuestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/start': {
      id: '/api/oauth/start'
      path: '/api/oauth/start'
      fullPath: '/api/oauth/start'
      preLoaderRoute: typeof ApiOauthStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/callback': {
      id: '/api/oauth/callback'
      path: '/api/oauth/callback'
      fullPath: '/api/oauth/callback'
      preLoaderRoute: typeof ApiOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ApiGuestsRoute: ApiGuestsRoute,
  RsvpIdRoute: RsvpIdRoute,
  ApiOauthCallbackRoute: ApiOauthCallbackRoute,
  ApiOauthStartRoute: ApiOauthStartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
